# Generated by Django 3.0.2 on 2020-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('passenger_class', models.CharField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')], max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('age', models.IntegerField()),
                ('siblings_or_spouse', models.IntegerField()),
                ('parents_or_children', models.IntegerField()),
                ('fare', models.FloatField()),
                ('prediction', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
